## Part 1

In [23]:
struct Planet
    pos::Vector{Int}
    vel::Vector{Int}
end

Planet(s::String) = Planet(parse.(Int, match(r"x=([\-0-9]+).*y=([\-0-9]+).*z=([\-0-9]+)", s).captures), zeros(Int, 3))
veldiff!(p1::Planet, p2::Planet) = (p1.vel .+= sign.(p2.pos .- p1.pos))
shift!(p::Planet) = (p.pos .+= p.vel)
energy(p::Planet) = sum(abs.(p.pos))*sum(abs.(p.vel))

planets = Planet.(readlines("input.txt"))

for i in 1:1000
    for p1 in planets, p2 in planets veldiff!(p1, p2) end
    for p in planets shift!(p) end
end

println(sum(energy.(planets)))

4-element Array{Planet,1}:
 Planet([15, -2, -6], [0, 0, 0]) 
 Planet([-5, -4, -11], [0, 0, 0])
 Planet([0, -6, 0], [0, 0, 0])   
 Planet([5, 9, 6], [0, 0, 0])    

## Part 2

In [79]:
## 1-dim problem
mutable struct Planet1
    pos::Int
    vel::Int
end

veldiff!(p1::Planet1, p2::Planet1) = (p1.vel += sign(p2.pos - p1.pos))
shift!(p::Planet1) = (p.pos += p.vel)

Base.:copy(p::Planet1) = Planet1(p.pos, p.vel)
equal(p1::Planet1, p2::Planet1) = p1.pos == p2.pos && p1.vel == p2.vel

function find_cycle(planets::Vector{Planet1})
    init = copy.(planets)
    @show init
    steps = 1
    while true
        for p1 in planets, p2 in planets veldiff!(p1, p2) end
        for p in planets shift!(p) end
        
        if all(equal.(planets, init)) return steps end
        steps += 1
    end
end

find_cycle (generic function with 1 method)

In [86]:
# planets = Planet.(["<x=-1, y=0, z=2>",
# "<x=2, y=-10, z=-7>",
# "<x=4, y=-8, z=8>",
# "<x=3, y=5, z=-1>"])

# planets = Planet.([
# "<x=-8, y=-10, z=0>",
# "<x=5, y=5, z=10>",
# "<x=2, y=-7, z=3>",
# "<x=9, y=-8, z=-3>"
# ])

planets = Planet.(readlines("input.txt"))
lcm([find_cycle([Planet1(p.pos[i], p.vel[i]) for p in planets]) for i in 1:3]...)

init = Planet1[Planet1(15, 0), Planet1(-5, 0), Planet1(0, 0), Planet1(5, 0)]
init = Planet1[Planet1(-2, 0), Planet1(-4, 0), Planet1(-6, 0), Planet1(9, 0)]
init = Planet1[Planet1(-6, 0), Planet1(-11, 0), Planet1(0, 0), Planet1(6, 0)]


326489627728984

In [83]:
lcm(18, 28, 44)

2772

In [82]:
9*14*22

2772

In [57]:
planets = [Planet1(0, 0), Planet1(4, 0)]

2-element Array{Planet1,1}:
 Planet1(0, 0)
 Planet1(4, 0)

In [58]:
find_cycle(planets)

init = Planet1[Planet1(0, 0), Planet1(4, 0)]


8

In [2]:
struct Planet
    pos::Vector{Int}
    vel::Vector{Int}
end

Planet(s::String) = Planet(parse.(Int, match(r"x=([\-0-9]+).*y=([\-0-9]+).*z=([\-0-9]+)", s).captures), zeros(Int, 3))

Planet

In [51]:
equal(Planet1(4, 0), Planet1(4, 0))

true

In [18]:
p1 = Planet("<x=15, y=-2, z=-6>")
p2 = Planet("<x=0, y=-6, z=0>")

Planet([0, -6, 0], [0, 0, 0])

In [19]:
veldiff!(p1, p2)

3-element Array{Int64,1}:
 -1
 -1
  1

In [20]:
p1

Planet([15, -2, -6], [-1, -1, 1])