## Part 1

In [348]:
# data = ".#..#
# .....
# #####
# ....#
# ...##"

# data = "......#.#.
# #..#.#....
# ..#######.
# .#.#.###..
# .#..#.....
# ..#....#.#
# #..#....#.
# .##.#..###
# ##...#..#.
# .#....####"

# data = "###
# ###
# ###"

# data = "#...
# .#..
# ..#.
# ...#"

# data = "#.#...#.#.
# .###....#.
# .#....#...
# ##.#.#.#.#
# ....#.#.#.
# .##..###.#
# ..#...##..
# ..##....##
# ......#...
# .####.###."

# data = ".#..#..###
# ####.###.#
# ....###.#.
# ..###.##.#
# ##.##.#.#.
# ....###..#
# ..#.#..#.#
# #..#.#.###
# .##...##.#
# .....#.#.."

data = ".#..##.###...#######
##.############..##.
.#.######.########.#
.###.#######.####.#.
#####.##.#.##.###.##
..#####..#.#########
####################
#.####....###.#.#.##
##.#################
#####.##.###..####..
..######..##.#######
####.##.####...##..#
.#####..#.######.###
##...#.##########...
#.##########.#######
.####.#.###.###.#.##
....##.##.###..#####
.#.#.###########.###
#.#.#.#####.####.###
###.##.####.##.#..##"

".#..##.###...#######\n##.############..##.\n.#.######.########.#\n.###.#######.####.#.\n#####.##.#.##.###.##\n..#####..#.#########\n####################\n#.####....###.#.#.##\n##.#################\n#####.##.###..####..\n..######..##.#######\n####.##.####...##..#\n.#####..#.######.###\n##...#.##########...\n#.##########.#######\n.####.#.###.###.#.##\n....##.##.###..#####\n.#.#.###########.###\n#.#.#.#####.####.###\n###.##.####.##.#..##"

In [322]:
data = readlines("input.txt")

34-element Array{String,1}:
 "#....#.....#...#.#.....#.#..#....#"
 "#..#..##...#......#.....#..###.#.#"
 "#......#.#.#.....##....#.#.....#.."
 "..#.#...#.......#.##..#..........."
 ".##..#...##......##.#.#..........."
 ".....#.#..##...#..##.....#...#.##."
 "....#.##.##.#....###.#........####"
 "..#....#..####........##.........#"
 "..#...#......#.#..#..#.#.##......#"
 ".............#.#....##.......#...#"
 ".#.#..##.#.#.#.#.......#.....#...."
 ".....##.###..#.....#.#..###.....##"
 ".....#...#.#.#......#.#....##....."
 ⋮                                   
 ".#.#.#..#............#..........#."
 "..##.....#....#....##..#.#.......#"
 "..##.....#.#......................"
 ".#..#...#....#.#.....#.........#.."
 "........#.............#.#........."
 "#...#.#......#.##....#...#.#.#...#"
 ".#.....#.#.....#.....#.#.##......#"
 "..##....#.....#.....#....#.##..#.."
 "#..###.#.#....#......#...#........"
 "..#......#..#....##...#.#.#...#..#"
 ".#.##.#.#.....#..#..#........##..."
 "....#...##.##.##....

In [325]:
collect.(data)

34-element Array{Array{Char,1},1}:
 ['#', '.', '.', '.', '.', '#', '.', '.', '.', '.'  …  '.', '#', '.', '.', '#', '.', '.', '.', '.', '#']
 ['#', '.', '.', '#', '.', '.', '#', '#', '.', '.'  …  '#', '.', '.', '#', '#', '#', '.', '#', '.', '#']
 ['#', '.', '.', '.', '.', '.', '.', '#', '.', '#'  …  '.', '#', '.', '.', '.', '.', '.', '#', '.', '.']
 ['.', '.', '#', '.', '#', '.', '.', '.', '#', '.'  …  '.', '.', '.', '.', '.', '.', '.', '.', '.', '.']
 ['.', '#', '#', '.', '.', '#', '.', '.', '.', '#'  …  '.', '.', '.', '.', '.', '.', '.', '.', '.', '.']
 ['.', '.', '.', '.', '.', '#', '.', '#', '.', '.'  …  '.', '#', '.', '.', '.', '#', '.', '#', '#', '.']
 ['.', '.', '.', '.', '#', '.', '#', '#', '.', '#'  …  '.', '.', '.', '.', '.', '.', '#', '#', '#', '#']
 ['.', '.', '#', '.', '.', '.', '.', '#', '.', '.'  …  '.', '.', '.', '.', '.', '.', '.', '.', '.', '#']
 ['.', '.', '#', '.', '.', '.', '#', '.', '.', '.'  …  '.', '#', '#', '.', '.', '.', '.', '.', '.', '#']
 ['.', '.', '.', '.'

In [279]:
hcat(collect.(split(data, '\n'))...)

4×4 Array{Char,2}:
 '#'  '.'  '.'  '.'
 '.'  '#'  '.'  '.'
 '.'  '.'  '#'  '.'
 '.'  '.'  '.'  '#'

In [326]:
#dd = hcat(collect.(split(data, '\n'))...)
dd = hcat(collect.(data)...)
asts = [[i[1], i[2]] for i in CartesianIndices(dd) if dd[i] == '#']

316-element Array{Array{Int64,1},1}:
 [1, 1]  
 [6, 1]  
 [12, 1] 
 [16, 1] 
 [18, 1] 
 [24, 1] 
 [26, 1] 
 [29, 1] 
 [34, 1] 
 [1, 2]  
 [4, 2]  
 [7, 2]  
 [8, 2]  
 ⋮       
 [31, 33]
 [5, 34] 
 [9, 34] 
 [10, 34]
 [12, 34]
 [13, 34]
 [15, 34]
 [16, 34]
 [23, 34]
 [26, 34]
 [29, 34]
 [30, 34]

In [287]:
op(x, y) = x[1]*y[2] - x[2]*y[1]
sp(x, y) = x[1]*y[1] + x[2]*y[2]

function ev(a, j)
    res = 0
    b = ones(Int, size(a)[1])
    b[j] = 0
    for i in 1:length(b)
        res += (sum(a[:, i]) - 1)*b[i]
#         println(a[:, i])
#         println(sum(a[:, i]) - 1)
        b[a[:, i] .== 1] .= 0
    end
    
    res
end

ev (generic function with 2 methods)

In [421]:
dd1 = op.(asts, asts')
dd2 = sp.(asts, asts')

316×316 Array{Int64,2}:
  2    7   13   17   19   25   27   30  …    49    50    57    60    63    64
  7   37   73   97  109  145  157  175      124   130   172   190   208   214
 13   73  145  193  217  289  313  349      214   226   310   346   382   394
 17   97  193  257  289  385  417  465      274   290   402   450   498   514
 19  109  217  289  325  433  469  523      304   322   448   502   556   574
 25  145  289  385  433  577  625  697  …   394   418   586   658   730   754
 27  157  313  417  469  625  677  755      424   450   632   710   788   814
 30  175  349  465  523  697  755  842      469   498   701   788   875   904
 35  205  409  545  613  817  885  987      544   578   816   918  1020  1054
  3    8   14   18   20   26   28   31       83    84    91    94    97    98
  6   26   50   66   74   98  106  118  …   128   132   160   172   184   188
  9   44   86  114  128  170  184  205      173   180   229   250   271   278
 10   50   98  130  146  194  210  234  

In [207]:
#map(x -> Int(x == 0), dd1 .- dd1[i, :]' .- dd1[: ,i])

2*(9 - 1) - sum(map(x -> Int(x > 0), dd2 .- dd2[1, :]' .- dd2[:, 1] .+ dd2[1, 1]) .*
    map(x -> Int(x == 0), dd1 .- dd1[1, :]' .- dd1[: ,1]))

-53

In [179]:
8 - div(sum(map(x -> Int(x > 0), dd2 .- dd2[5, :]' .- dd2[:, 5] .+ dd2[5, 5]) .*
    map(x -> Int(x == 0), dd1 .- dd1[5, :]' .- dd1[: ,5])) - 8, 2)

8

In [208]:
maximum([length(asts) - 1 - 
    div(sum(map(x -> Int(x > 0), dd2 .- dd2[i, :]' .- dd2[:, i] .+ dd2[i, i]) .*
    map(x -> Int(x == 0), dd1 .- dd1[i, :]' .- dd1[: ,i])) - length(asts) + 1, 2)
    for i in 1:length(asts)])

32

In [209]:
argmax([length(asts) - 1 - 
    div(sum(map(x -> Int(x > 0), dd2 .- dd2[i, :]' .- dd2[:, i] .+ dd2[i, i]) .*
    map(x -> Int(x == 0), dd1 .- dd1[i, :]' .- dd1[: ,i])) - length(asts) + 1, 2)
    for i in 1:length(asts)])

3

In [422]:
maximum([
     length(asts) - 1 - ev(map(x -> Int(x > 0), dd2 .- dd2[i, :]' .- dd2[:, i] .+ dd2[i, i]) .*
    map(x -> Int(x == 0), dd1 .- dd1[i, :]' .- dd1[: , i]), i) for i in 1:length(asts)])

267

In [423]:
argmax([
     length(asts) - 1 - ev(map(x -> Int(x > 0), dd2 .- dd2[i, :]' .- dd2[:, i] .+ dd2[i, i]) .*
    map(x -> Int(x == 0), dd1 .- dd1[i, :]' .- dd1[: , i]), i) for i in 1:length(asts)])

266

In [292]:
ev(map(x -> Int(x > 0), dd2 .- dd2[34, :]' .- dd2[:, 34] .+ dd2[34, 34]) .*
    map(x -> Int(x == 0), dd1 .- dd1[34, :]' .- dd1[: ,34]), 34)

6

In [288]:
ev(map(x -> Int(x > 0), dd2 .- dd2[1, :]' .- dd2[:, 1] .+ dd2[1, 1]) .*
    map(x -> Int(x == 0), dd1 .- dd1[1, :]' .- dd1[: ,1]), 1)

2

In [283]:
map(x -> Int(x > 0), dd2 .- dd2[1, :]' .- dd2[:, 1] .+ dd2[1, 1]) .*
    map(x -> Int(x == 0), dd1 .- dd1[1, :]' .- dd1[: ,1])

4×4 Array{Int64,2}:
 0  0  0  0
 0  1  1  1
 0  1  1  1
 0  1  1  1

In [251]:
map(x -> Int(x > 0), dd2 .- dd2[34, :]' .- dd2[:, 34] .+ dd2[34, 34])[32, 35]

0

In [237]:
[println(sort(findall(map(x -> Int(x == 0), dd1 .- dd1[34, :]' .- dd1[: ,34])[i, :] .== 1))) for i in 1:length(asts)]

[1, 34]
[2, 34]
[3, 34]
[4, 34]
[5, 9, 15, 34]
[6, 34]
[7, 34]
[8, 34]
[5, 9, 15, 34]
[10, 34]
[11, 34]
[12, 34]
[13, 34]
[14, 34]
[5, 9, 15, 34]
[16, 34]
[17, 34]
[18, 20, 24, 28, 34, 37]
[19, 34]
[18, 20, 24, 28, 34, 37]
[21, 34]
[22, 34]
[23, 34]
[18, 20, 24, 28, 34, 37]
[25, 34]
[26, 34, 40]
[27, 34, 39]
[18, 20, 24, 28, 34, 37]
[29, 34]
[30, 34]
[31, 34, 36]
[32, 33, 34, 35]
[32, 33, 34, 35]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
[32, 33, 34, 35]
[31, 34, 36]
[18, 20, 24, 28, 34, 37]
[34, 38]
[27, 34, 39]
[26, 34, 40]


40-element Array{Nothing,1}:
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 ⋮      
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing

In [223]:
length(asts)

40

In [220]:
argmax([x == [6, 9] for x in asts])

34

In [150]:
maximum([length(asts) - div(sum(map(x -> Int(x == 0), dd .- dd[i, :]' .- dd[: ,i])) - 3*length(asts), 2) - 2 for i in 1:length(asts)])

6

In [142]:
xx = [length(asts) - div(sum(map(x -> Int(x == 0), dd .- dd[i, :]' .- dd[: ,i])) - 3*length(asts), 2) - 2 for i in 1:length(asts)]
argmax(xx .== 32)

3

In [157]:
map(x -> Int(x == 0), dd .- dd[5, :]' .- dd[: ,5])

9×9 Array{Int64,2}:
 1  0  0  0  1  0  0  0  1
 0  1  0  0  1  0  0  1  0
 0  0  1  0  1  0  1  0  0
 0  0  0  1  1  1  0  0  0
 1  1  1  1  1  1  1  1  1
 0  0  0  1  1  1  0  0  0
 0  0  1  0  1  0  1  0  0
 0  1  0  0  1  0  0  1  0
 1  0  0  0  1  0  0  0  1

In [156]:
length(asts) - div(sum(map(x -> Int(x == 0), dd .- dd[5, :]' .- dd[: ,5])) - 3*length(asts), 2) - 2

4

In [95]:
asts[7]

2-element Array{Int64,1}:
 5
 3

In [103]:
dd[5, 6], dd[5, 7], dd[7, 6]

(-3, -6, 3)

In [13]:
[i for i in CartesianIndices(dd) if dd[i] == '#']

10-element Array{CartesianIndex{2},1}:
 CartesianIndex(2, 1)
 CartesianIndex(5, 1)
 CartesianIndex(1, 3)
 CartesianIndex(2, 3)
 CartesianIndex(3, 3)
 CartesianIndex(4, 3)
 CartesianIndex(5, 3)
 CartesianIndex(5, 4)
 CartesianIndex(4, 5)
 CartesianIndex(5, 5)

In [270]:
dd[:, 1]

10-element Array{Char,1}:
 '.'
 '.'
 '.'
 '.'
 '.'
 '.'
 '#'
 '.'
 '#'
 '.'

(10, 10)

## Part 2

In [347]:
atand(-1, 0) + 180

90.0

In [420]:
# dd = hcat(collect.(split(data, '\n'))...)
data = readlines("input.txt")
dd = hcat(collect.(data)...)
asts = [[i[1], i[2]] for i in CartesianIndices(dd) if dd[i] == '#']

316-element Array{Array{Int64,1},1}:
 [1, 1]  
 [6, 1]  
 [12, 1] 
 [16, 1] 
 [18, 1] 
 [24, 1] 
 [26, 1] 
 [29, 1] 
 [34, 1] 
 [1, 2]  
 [4, 2]  
 [7, 2]  
 [8, 2]  
 ⋮       
 [31, 33]
 [5, 34] 
 [9, 34] 
 [10, 34]
 [12, 34]
 [13, 34]
 [15, 34]
 [16, 34]
 [23, 34]
 [26, 34]
 [29, 34]
 [30, 34]

In [424]:
# 206
argmax([a[1] == 12 && a[2] == 14 for a in asts])
id = 206

# 266
id = 266

ox = [0, 1]
oy = [-1, 0]

asts2 = [[a[1] - asts[id][1], a[2] - asts[id][2]] for a in asts]
asts3 = [[sp(a, ox), sp(a, oy)] for a in asts2]
asts4 = [[a[1]^2 + a[2]^2, atand(a[2], a[1]) + 180] for a in asts3]
asts4 = [[a[1], a[2] == 360.0 ? 0.0 : a[2]] for a in asts4]

316-element Array{Array{Float64,1},1}:
 [1460.0, 317.1210963966614] 
 [1225.0, 323.13010235415595]
 [1009.0, 331.82140989004085]
 [905.0, 338.5522636728947]  
 [865.0, 342.18111108547726] 
 [793.0, 353.8844964337146]  
 [785.0, 357.95459151111277] 
 [788.0, 4.085616779974885]  
 [833.0, 14.036243467926482] 
 [1405.0, 316.0809241866607] 
 [1258.0, 319.5739212599009] 
 [1129.0, 323.47114463301483]
 [1090.0, 324.86580694308435]
 ⋮                           
 [32.0, 135.0]               
 [509.0, 257.19573393471325] 
 [349.0, 254.47588900324575] 
 [314.0, 253.6104596659652]  
 [250.0, 251.56505117707798] 
 [221.0, 250.34617594194668] 
 [169.0, 247.3801350519596]  
 [146.0, 245.55604521958347] 
 [41.0, 218.65980825409008]  
 [26.0, 191.30993247402023]  
 [29.0, 158.19859051364818]  
 [34.0, 149.03624346792648]  

In [397]:
isless1(x, y) = x[2] < y[2] || (x[2] == y[2] && x[1] < y[1])

isless1 (generic function with 1 method)

In [425]:
p1 = sortperm(asts4, lt = (x, y) -> x[2] < y[2] || (x[2] == y[2] && x[1] < y[1]))

316-element Array{Int64,1}:
 176
 169
 117
  89
  17
 126
   8
  18
 170
 185
 194
  19
 127
   ⋮
  79
 115
  28
   6
 184
  16
 135
 116
  88
  54
  29
   7

In [401]:
asts4[p1]

300-element Array{Array{Float64,1},1}:
 [1.0, 0.0]                 
 [4.0, 0.0]                 
 [9.0, 0.0]                 
 [16.0, 0.0]                
 [25.0, 0.0]                
 [36.0, 0.0]                
 [49.0, 0.0]                
 [64.0, 0.0]                
 [81.0, 0.0]                
 [100.0, 0.0]               
 [121.0, 0.0]               
 [144.0, 0.0]               
 [145.0, 4.763641690726189] 
 ⋮                          
 [153.0, 345.9637565320735] 
 [178.0, 347.00538320808346]
 [85.0, 347.4711922908485]  
 [26.0, 348.69006752597977] 
 [104.0, 348.69006752597977]
 [37.0, 350.5376777919744]  
 [148.0, 350.5376777919744] 
 [173.0, 351.25383773744477]
 [50.0, 351.86989764584405] 
 [101.0, 354.28940686250036]
 [122.0, 354.8055710922652] 
 [145.0, 355.2363583092738] 

In [426]:
asts5 = foldl((x, y) -> push!(x, x[end][1] == y[2] ? [y[2], x[end][2] + 1] : [y[2], 1]), asts4[p1]; init = [[asts4[p1][1][2], 0]])[2:end]

316-element Array{Array{Float64,1},1}:
 [0.0, 1.0]               
 [0.0, 2.0]               
 [0.0, 3.0]               
 [0.0, 4.0]               
 [2.121096396661443, 1.0] 
 [3.5763343749973444, 1.0]
 [4.085616779974885, 1.0] 
 [4.236394799058814, 1.0] 
 [4.763641690726189, 1.0] 
 [5.710593137499643, 1.0] 
 [6.340191745909891, 1.0] 
 [6.340191745909891, 2.0] 
 [7.125016348901795, 1.0] 
 ⋮                        
 [351.86989764584405, 2.0]
 [353.2901631922431, 1.0] 
 [353.418055344822, 1.0]  
 [353.8844964337146, 1.0] 
 [354.28940686250036, 1.0]
 [355.7636052009412, 1.0] 
 [356.18592516570965, 1.0]
 [356.63353933657015, 1.0]
 [357.1375947738883, 1.0] 
 [357.5104470780009, 1.0] 
 [357.79740183823424, 1.0]
 [357.95459151111277, 1.0]

In [427]:
p2 = sortperm(asts5, lt = (x, y) -> x[2] < y[2] || (x[2] == y[2] && x[1] < y[1]))

316-element Array{Int64,1}:
   1
   5
   6
   7
   8
   9
  10
  11
  13
  14
  15
  17
  18
   ⋮
 109
 193
 292
 110
 194
 293
 111
 195
 112
 196
 197
 198

In [429]:
z = asts[p1][p2][200]
(z[1] - 1)*100 + (z[2] - 1)

1309

In [395]:
asts4[191]

2-element Array{Float64,1}:
 1.0
 0.0

In [388]:
asts3[191]

2-element Array{Int64,1}:
 -1
  0

In [393]:
atand(1, 0)

90.0