## Part 1

In [4]:
ss = readlines("input.txt")

9-element Array{String,1}:
 "Vixen can fly 19 km/s for 7 seconds, but then must rest for 124 seconds."  
 "Rudolph can fly 3 km/s for 15 seconds, but then must rest for 28 seconds." 
 "Donner can fly 19 km/s for 9 seconds, but then must rest for 164 seconds." 
 "Blitzen can fly 19 km/s for 9 seconds, but then must rest for 158 seconds."
 "Comet can fly 13 km/s for 7 seconds, but then must rest for 82 seconds."   
 "Cupid can fly 25 km/s for 6 seconds, but then must rest for 145 seconds."  
 "Dasher can fly 14 km/s for 3 seconds, but then must rest for 38 seconds."  
 "Dancer can fly 3 km/s for 16 seconds, but then must rest for 37 seconds."  
 "Prancer can fly 25 km/s for 6 seconds, but then must rest for 143 seconds."

In [2]:
struct Deer
    name::String
    fly::Int
    period::Int
    rest::Int
end

In [11]:
deers = Deer[]
for s in ss
    m = match(r"^([^ ]+) [^0-9]*([0-9]+) km/s for ([0-9]+).*rest[^0-9]*([0-9]+)", s)
    push!(deers, Deer(m[1], parse.(Int, m.captures[2:end])...))
end

deers

9-element Array{Deer,1}:
 Deer("Vixen", 19, 7, 124)  
 Deer("Rudolph", 3, 15, 28) 
 Deer("Donner", 19, 9, 164) 
 Deer("Blitzen", 19, 9, 158)
 Deer("Comet", 13, 7, 82)   
 Deer("Cupid", 25, 6, 145)  
 Deer("Dasher", 14, 3, 38)  
 Deer("Dancer", 3, 16, 37)  
 Deer("Prancer", 25, 6, 143)

In [12]:
function distance(d::Deer, t)
    res = 0
    while t > 0
        t0 = min(d.period, t)
        res += d.fly*t0
        t -= t0
        t0 = min(d.rest, t)
        t -= t0
    end
    res
end

distance (generic function with 1 method)

In [16]:
maximum(map(x -> distance(x, 2503), deers))

2660

## Part 2

In [25]:
function distance2(d::Deer, t)
    d.fly*((t ÷ (d.period + d.rest))*d.period + min(mod(t, d.period + d.rest), d.period))
end

distance2 (generic function with 1 method)

In [28]:
distance2(deers[2], 2503)

2637

In [27]:
distance(deers[2], 2503)

2637

In [24]:
(2503 ÷ (deers[1].period + deers[1].rest))*deers[1].fly*deers[1].period

2527

In [37]:
res = zeros(Int, length(deers))
for i in 1:2503
    dist = [distance2(d, i) for d in deers]
    m = maximum(dist)
    res += dist .== m
end
res

9-element Array{Int64,1}:
  469
  188
  589
 1256
  158
  307
    9
    0
  504