In [21]:
function read_data(inp = "input.txt")
    arr = hcat(collect.(readlines(inp))...)
    arr = map(x -> x == '.' ? 0 : 1, arr)
    println(size(arr))
    arr0 = zeros(Int, size(arr)[1] + 2, size(arr)[2] + 2)
    arr0[2:(size(arr)[1] + 1), 2:(size(arr)[2] + 1)] .= arr
    arr0
end

read_data (generic function with 2 methods)

In [22]:
read_data()

(5, 5)


7×7 Array{Int64,2}:
 0  0  0  0  0  0  0
 0  1  0  1  1  0  0
 0  1  1  1  0  1  0
 0  0  0  0  1  1  0
 0  1  1  0  0  1  0
 0  1  1  1  0  0  0
 0  0  0  0  0  0  0

In [47]:
function tick(arr)
    arr0 = copy(arr)
    dirs = [[1, 0], [0, 1], [-1, 0], [0, -1]]
    for i in 2:6, j in 2:6
        adj = sum([arr[i + d[1], j + d[2]] for d in dirs])
        if arr[i, j] == 0 && (adj == 1 || adj == 2) arr0[i, j] = 1 end
        if arr[i, j] == 1 && adj != 1 arr0[i, j] = 0 end
    end
    
    arr0
end

function biodiversity(arr)
    arr = arr[2:6, 2:6]
    res = 0
    for i in 1:5
        for j in 1:5
            res += arr[i, j] * 2^((j - 1)*5 + i - 1)
        end
    end
    res
end

biodiversity (generic function with 1 method)

In [48]:
function showgrid(arr)
    for j in 2:6
        for i in 2:6
            print(arr[i, j] == 0 ? '.' : '#')
        end
        print("\n")
    end
end

showgrid (generic function with 1 method)

In [53]:
function part1()
    arr = read_data()
    bios = Set{Int}()
    while true
        bio = biodiversity(arr)
        if !(bio in bios)
            push!(bios, bio)
        else
            println("Part 1: ", bio)
            break
        end
        arr = tick(arr)
    end
end

part1 (generic function with 1 method)

In [54]:
part1()

(5, 5)
Part 1: 23846449


In [49]:
arr = read_data("test2.txt")
showgrid(arr)

(5, 5)
.....
.....
.....
#....
.#...


In [39]:
showgrid(tick(arr))

#..#.
####.
###.#
##.##
.##..


In [50]:
biodiversity(arr)

2129920

## Part 2

In [13]:
struct Cell
    x::Int
    y::Int
    d::Int
end

function neighbours(c::Cell)
    res = Cell[]
    dirs = [[0, 1], [1, 0], [0, -1], [-1, 0]]
    for d in dirs
        x1 = c.x + d[1]
        y1 = c.y + d[2]
        if x1 == 0
            push!(res, Cell(2, 3, c.d - 1))
        elseif x1 == 6
            push!(res, Cell(4, 3, c.d - 1))
        elseif y1 == 0
            push!(res, Cell(3, 2, c.d - 1))
        elseif y1 == 6
            push!(res, Cell(3, 4, c.d - 1))
        elseif x1 == 3 && y1 == 3
            if c.x == 2
                append!(res, [
                        Cell(1, 1, c.d + 1),
                        Cell(1, 2, c.d + 1),
                        Cell(1, 3, c.d + 1),
                        Cell(1, 4, c.d + 1),
                        Cell(1, 5, c.d + 1)
                        ])
            elseif c.x == 4
                append!(res, [
                        Cell(5, 1, c.d + 1),
                        Cell(5, 2, c.d + 1),
                        Cell(5, 3, c.d + 1),
                        Cell(5, 4, c.d + 1),
                        Cell(5, 5, c.d + 1)
                        ])
            elseif c.y == 2
                append!(res, [
                        Cell(1, 1, c.d + 1),
                        Cell(2, 1, c.d + 1),
                        Cell(3, 1, c.d + 1),
                        Cell(4, 1, c.d + 1),
                        Cell(5, 1, c.d + 1)
                        ])
            else
                append!(res, [
                        Cell(1, 5, c.d + 1),
                        Cell(2, 5, c.d + 1),
                        Cell(3, 5, c.d + 1),
                        Cell(4, 5, c.d + 1),
                        Cell(5, 5, c.d + 1)
                        ])
            end
        else
            push!(res, Cell(x1, y1, c.d))
        end
    end
    res
end

function read_data(inp = "input.txt")
    arr = hcat(collect.(readlines(inp))...)
    arr0 = Set{Cell}()
    for i in 1:5, j in 1:5
        if arr[i, j] == '#' push!(arr0, Cell(i, j, 0)) end
    end
    arr0
end

read_data (generic function with 2 methods)

In [58]:
arr = read_data("test2.txt")

Set(Cell[Cell(1, 4, 0), Cell(2, 5, 0)])

In [18]:
function tick(arr)
    res = Set{Cell}()
    mind, maxd = [f([c.d for c in arr]) for f in (x -> minimum(x) - 1, x -> maximum(x) + 1)]
    for d in mind:maxd
        for i in 1:5, j in 1:5
            if i == 3 && j == 3 continue end
            c = Cell(i, j, d)
            adj = sum([neighbour in arr for neighbour in neighbours(c)])
            if (c in arr) && (adj == 1) push!(res, c) end
            if !(c in arr) && ((adj == 1) || (adj == 2)1) push!(res, c) end
        end
    end
    
    res
end

tick (generic function with 1 method)

In [3]:
function show_grid(arr)
    mind, maxd = [f([c.d for c in arr]) for f in (minimum, maximum)]
    for d in mind:maxd
        println("Depth: ", d)
        for j in 1:5
            for i in 1:5
                Cell(i, j, d) in arr ? print('#') : print('.')
            end
            print("\n")
        end
        println("=============")
    end
end

show_grid (generic function with 1 method)

In [92]:
arr = read_data()

Set(Cell[Cell(1, 3, 0), Cell(1, 4, 0), Cell(4, 5, 0), Cell(4, 2, 0), Cell(2, 3, 0), Cell(5, 2, 0), Cell(2, 1, 0), Cell(5, 3, 0), Cell(2, 2, 0), Cell(5, 1, 0), Cell(3, 5, 0), Cell(1, 1, 0), Cell(3, 4, 0), Cell(4, 1, 0), Cell(2, 5, 0)])

In [95]:
show_grid(tick(arr))

Depth: -1
.....
.....
.....
.....
.####
Depth: 0
.....
..#..
...##
..###
.#.##


In [22]:
function part2()
    arr = read_data("input.txt")
    for i in 1:200
        arr = tick(arr)
    end
    println("Part 2: ", length(arr))
end

part2 (generic function with 1 method)

In [23]:
part2()

Part 2: 1934


In [14]:
arr = read_data("test.txt")

Set(Cell[Cell(1, 2, 0), Cell(4, 2, 0), Cell(4, 3, 0), Cell(5, 1, 0), Cell(1, 5, 0), Cell(3, 4, 0), Cell(1, 3, 0), Cell(5, 3, 0)])

In [15]:
neighbours(Cell(1, 1, 0))

4-element Array{Cell,1}:
 Cell(1, 2, 0) 
 Cell(2, 1, 0) 
 Cell(3, 2, -1)
 Cell(2, 3, -1)

## Misc

In [1]:
abstract type AbstractCell end
abstract type AbstractGrid end

adjacent(cell::S, grid::T) where {T <: AbstractGrid, S <: AbstractCell} = throw("Unimplemented")
rule(cell::S, neighbours::Vector{S}, grid::T) where {T <: AbstractGrid, S <: AbstractCell} = throw("Unimplemented")
Base.:in(cell::S, grid::T) where {T <: AbstractGrid, S <: AbstractCell} = cell in grid.set
Base.:push!(cell::S, grid::T) where {T <: AbstractGrid, S <: AbstractCell} = push!(grid.set, cell)
cells()

In [ ]:
Base.:iterate()

In [8]:
function tick(grid::T) where T <: AbstractGrid
    res = T(grid)
    for cell in cells(grid)
        adj = [neighbour for neighbour in adjacent(cell, grid) if neighbour in grid]
        if rule(cell, grid, adj) push!(cell, res) end
    end
    
    res
end

tick (generic function with 1 method)

In [6]:
struct D2Cell <: AbstractCell
    x::Int
    y::Int
end

struct Eris <: AbstractGrid
    set::Set{D2Cell}
    h::Int
    w::Int
end

Eris(h::T, w::T) where T <: Integer = Eris(Set{D2Cell}(), h, w)
Eris(eris::Eris) = Eris(Set{D2Cell}(), eris.h, eris.w)
function Eris(ss::Vector{String})
    arr = hcat(collect.(ss)...)
    arr0 = Set{D2Cell}()
    for i in 1:5, j in 1:5
        if arr[i, j] == '#' push!(arr0, D2Cell(i, j)) end
    end
    Eris(arr0, 5, 5)
end

function adjacent(cell::D2Cell, grid::Eris)
    dirs = [[0, 1], [1, 0], [0, -1], [-1, 0]]
    res = D2Cell[]
    for d in dirs
        x = cell.x + d[1]
        y = cell.y + d[2]
        if (x != 0) && (x != grid.w + 1) && (y != 0) && (y != grid.h + 1) push!(res, D2Cell(x, y)) end
    end
    res
end

rule(cell::D2Cell, adj::Vector{D2Cell}, grid::Eris) = ((cell in grid) && (length(adj) == 1)) || (!(cell in grid) && (length(adj) in [1, 2]))

rule (generic function with 3 methods)

In [32]:
UInt8(10) isa Integer

true

In [44]:
function Eris(ss::Vector{String})
    arr = hcat(collect.(ss)...)
    arr0 = Set{2dCell}()
    for i in 1:5, j in 1:5
        if arr[i, j] == '#' push!(arr0, 2dCell(i, j)) end
    end
    Eris(arr0, 5, 5)
end

Eris (generic function with 1 method)

In [3]:
grid = Eris(readlines("input.txt"))

Eris(Set(D2Cell[D2Cell(1, 1), D2Cell(3, 5), D2Cell(2, 5), D2Cell(2, 2), D2Cell(4, 1), D2Cell(4, 5), D2Cell(1, 3), D2Cell(4, 2), D2Cell(2, 1), D2Cell(5, 1), D2Cell(5, 2), D2Cell(5, 3), D2Cell(1, 4), D2Cell(3, 4), D2Cell(2, 3)]), 5, 5)

In [8]:
adjacent(D2Cell(1, 1), grid)

2-element Array{D2Cell,1}:
 D2Cell(1, 2)
 D2Cell(2, 1)

In [4]:
neighbours = [neighbour for neighbour in adjacent(D2Cell(1, 1), grid) if neighbour in grid]

1-element Array{D2Cell,1}:
 D2Cell(2, 1)

In [7]:
rule(D2Cell(1, 1), neighbours, grid)

true

In [9]:
tick(grid)

UndefVarError: UndefVarError: cells not defined