## Part 1

In [11]:
data = sort(readlines("test_input.txt"))

17-element Array{String,1}:
 "[1518-11-01 00:00] Guard #10 begins shift"
 "[1518-11-01 00:05] falls asleep"          
 "[1518-11-01 00:25] wakes up"              
 "[1518-11-01 00:30] falls asleep"          
 "[1518-11-01 00:55] wakes up"              
 "[1518-11-01 23:58] Guard #99 begins shift"
 "[1518-11-02 00:40] falls asleep"          
 "[1518-11-02 00:50] wakes up"              
 "[1518-11-03 00:05] Guard #10 begins shift"
 "[1518-11-03 00:24] falls asleep"          
 "[1518-11-03 00:29] wakes up"              
 "[1518-11-04 00:02] Guard #99 begins shift"
 "[1518-11-04 00:36] falls asleep"          
 "[1518-11-04 00:46] wakes up"              
 "[1518-11-05 00:03] Guard #99 begins shift"
 "[1518-11-05 00:45] falls asleep"          
 "[1518-11-05 00:55] wakes up"              

In [12]:
m = match(r"\[([0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]) ..:([0-9][0-9])\] Guard #([0-9]+) .*", data[1])

RegexMatch("[1518-11-01 00:00] Guard #10 begins shift", 1="1518-11-01", 2="00", 3="10")

In [66]:
function aoc1(data)
    data = sort!(data)
    recs = Dict{Int, Dict{String, Vector{Int}}}()
    cur = 0
    fall = 0
    for x in data
        m = match(r"\[([0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]) ..:([0-9][0-9])\] Guard #([0-9]+) .*", x)
        if m != nothing
            cur = parse(Int, m[3])
            continue
        end
        m = match(r"\[([0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]) ..:([0-9][0-9])\] falls asleep$", x)
        if m != nothing
            fall = parse(Int, m[2])
            continue
        end
        
        m = match(r"\[([0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]) ..:([0-9][0-9])\] wakes up$", x)
        if !(cur in keys(recs))
            recs[cur] = Dict{String, Vector{Int}}([m[1] => zeros(Int, 60)])
        end
            
        if !(m[1] in keys(recs[cur]))
            recs[cur][m[1]] = zeros(Int, 60)
        end

        for i in (fall + 1):(parse(Int, m[2]))
            recs[cur][m[1]][i] = 1
        end
    end
    
    sleepers = Dict( key => sum(sum.(values(value))) for (key, value) in recs)
    maxid = -1
    maxsleep = 0
    for (k, v) in sleepers
        if v > maxsleep 
            maxid = k
            maxsleep = v
        end
    end

    x = zeros(Int, 60)
    for v1 in values(recs[maxid])
        x = x .+ v1
    end
    
    minute = argmax(x)

    (minute - 1)*maxid
end

aoc1 (generic function with 1 method)

In [67]:
data = readlines("test_input.txt")
println(aoc1(data))

240


In [68]:
data = readlines("input.txt")
println(aoc1(data))

60438


## Part 2

In [70]:
function max_minute(d)
    x = zeros(Int, 60)
    for v1 in values(d)
        x = x .+ v1
    end
    
    (argmax(x), x[argmax(x)])
end

function aoc2(data)
    data = sort!(data)
    recs = Dict{Int, Dict{String, Vector{Int}}}()
    cur = 0
    fall = 0
    for x in data
        m = match(r"\[([0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]) ..:([0-9][0-9])\] Guard #([0-9]+) .*", x)
        if m != nothing
            cur = parse(Int, m[3])
            continue
        end
        m = match(r"\[([0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]) ..:([0-9][0-9])\] falls asleep$", x)
        if m != nothing
            fall = parse(Int, m[2])
            continue
        end
        
        m = match(r"\[([0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]) ..:([0-9][0-9])\] wakes up$", x)
        if !(cur in keys(recs))
            recs[cur] = Dict{String, Vector{Int}}([m[1] => zeros(Int, 60)])
        end
            
        if !(m[1] in keys(recs[cur]))
            recs[cur][m[1]] = zeros(Int, 60)
        end

        for i in (fall + 1):(parse(Int, m[2]))
            recs[cur][m[1]][i] = 1
        end
    end
    
    sleepers = Dict( key => max_minute(value) for (key, value) in recs)
    maxid = -1
    maxsleep = 0
    for (k, v) in sleepers
        if v[2] > maxsleep
            maxid = k
            maxsleep = v[2]
        end
    end

    (sleepers[maxid][1] - 1)*maxid
end

aoc2 (generic function with 1 method)

In [71]:
data = readlines("test_input.txt")
println(aoc2(data))

4455


In [72]:
data = readlines("input.txt")
println(aoc2(data))

47989


In [74]:
'c' - 'C'

32

In [75]:
'a' - 'A'

32

In [76]:
'A' - 'a'

-32

In [116]:
t = collect("dabAcCaCBAcCcaDA")

16-element Array{Char,1}:
 'd'
 'a'
 'b'
 'A'
 'c'
 'C'
 'a'
 'C'
 'B'
 'A'
 'c'
 'C'
 'c'
 'a'
 'D'
 'A'

In [125]:
z = findall(abs.(t .- vcat(t[2:end], [t[end]])) .== 32)

0-element Array{Int64,1}

In [126]:
length(z)

0

In [115]:
sort(vcat(z, z .+ 1))

4-element Array{Int64,1}:
  5
  6
 11
 12

In [124]:
deleteat!(t, sort(vcat(z, z .+ 1)))

10-element Array{Char,1}:
 'd'
 'a'
 'b'
 'C'
 'B'
 'A'
 'c'
 'a'
 'D'
 'A'

In [120]:
t

12-element Array{Char,1}:
 'd'
 'a'
 'b'
 'A'
 'a'
 'C'
 'B'
 'A'
 'c'
 'a'
 'D'
 'A'

In [122]:
t .- vcat(t[2:end], [t[end]])

12-element Array{Int64,1}:
   3
  -1
  33
 -32
  30
   1
   1
 -34
   2
  29
   3
   0