In [1]:
readline("input19.txt")

"109,424,203,1,21101,11,0,0,1105,1,282,21102,1,18,0,1105,1,259,2102,1,1,221,203,1,21102,1,31,0,1105,1,282,21102,38,1,0,1105,1,259,20101,0,23,2,22102,1,1,3,21101,1,0,1,21101,57,0,0,1105,1,303,2101,0,1,222,21002,221,1,3,21002,221,1,2,21102,1,259,1,21101,0,80,0,1105,1,225,21102,83,1,2,21102,1,91,0,1106,0,303,2101,0,1,223,20102,1,222,4,21101,0,259,3,21101,0,225,2,21101,225,0,1,21101,118,0,0,1106,0,225,20101,0,222,3,21101,34,0,2,21101,133,0,0,1105,1,303,21202,1,-1,1,22001,223,1,1,21102,1,148,0,1106,0,259,1201,1,0,223,20102,1,221,4,20101,0,222,3,21101,12,0,2,1001,132,-2,224,1002,224,2,224,1001,224,3,224,1002,132,-1,132,1,224,132,224,21001,224,1,1,21101,195,0,0,105,1,108,20207,1,223,2,20101,0,23,1,21102,1,-1,3,21102,214,1,0,1105,1,303,22101,1,1,1,204,1,99,0,0,0,0,109,5,1202,-4,1,249,22101,0,-3,1,22101,0,-2,2,21201,-1,0,3,21101,0,250,0,1105,1,225,21201,1,0,-4,109,-5,2106,0,0,109,3,22107,0,-2,-1,21202,-1,2,-1,21201,-1,-1,-1,22202,-1,-2,-2,109,-3,2106,0,0,109,3,21207,-2,0,-1,1206,-1,294,104,0,99

In [1]:
s = "109,424,203,1"

"109,424,203,1"

In [2]:
str2prog(s) = parse.(Int, split(s, ","))

str2prog (generic function with 1 method)

In [68]:
struct Instruction
    op::Int
    modes::Vector{Int}
    result::Bool
    name::String
    lng::Int
end

function Instruction(op_code::Int)
    ops = Dict{Int, Tuple{Int, Bool, String}}(
        1 => (3, true, "ADD"),
        2 => (3, true, "MUL"),
        3 => (1, true, "INP"),
        4 => (1, false, "OUT"),
        5 => (2, false, "NEZ"),
        6 => (2, false, "EQZ"),
        7 => (3, true, "LES"),
        8 => (3, true, "EQL"),
        9 => (1, false, "MVP"),
        99 => (0, false, "EOP")
    )

    op = mod(op_code, 100)
    modes_code = div(op_code, 100)
    if op in keys(ops)
        modes = zeros(ops[op][1])
        for i in 1:ops[op][1]
            modes[i] = mod(modes_code, 10)
            modes_code = div(modes_code, 10)
        end

        return Instruction(op, modes, ops[op][2], ops[op][3], ops[op][1])
    else
        return Instruction(op_code, [], false, "ERR", 0)
    end
end

Instruction

In [4]:
struct Operation
    cur::Int
    name::String
    args::Vector{String}
end

In [6]:
code = str2prog(s)

4-element Array{Int64,1}:
 109
 424
 203
   1

In [63]:
function disassemble(code::Vector{Int})
    res = Operation[]
    cur = 1
    while cur <= length(code)
        instruction = Instruction(code[cur])
        pos = cur - 1
        args = String[]
        for j in 1:instruction.lng
            cur += 1
            if instruction.modes[j] == 0
                push!(args, "M" * string(code[cur]))
            elseif instruction.modes[j] == 1
                push!(args, string(code[cur]))
            else
                push!(args, "R" * string(code[cur]))
            end
        end
        cur += 1
        if instruction.name != "ERR"
            push!(res, Operation(pos, instruction.name, args))
        else
            push!(res, Operation(pos, instruction.name, [string(instruction.op)]))
        end
    end
    
    res
end

disassemble (generic function with 1 method)

In [39]:
asm = disassemble(str2prog(s))

2-element Array{Operation,1}:
 Operation(0, "MVP", ["424"])
 Operation(2, "INP", ["R1"]) 

In [38]:
function show_asm(asm)
    for el in asm
        print(("0"^6*string(el.cur))[(end-2):end], ":\t")
        print(el.name, '\t')
        println(join(el.args, '\t'))
    end
end

show_asm (generic function with 1 method)

In [40]:
show_asm(asm)

000:	MVP	424
002:	INP	R1


In [69]:
readline("input19.txt") |> x -> str2prog(x) |> x -> disassemble(x) |> x -> show_asm(x)
# code = str2prog(readline("input19.txt"))

000:	MVP	424
002:	INP	R1
004:	ADD	11	0	R0
008:	NEZ	1	282
011:	MUL	1	18	R0
015:	NEZ	1	259
018:	MUL	1	R1	M221
022:	INP	R1
024:	MUL	1	31	R0
028:	NEZ	1	282
031:	MUL	38	1	R0
035:	NEZ	1	259
038:	ADD	0	M23	R2
042:	MUL	1	R1	R3
046:	ADD	1	0	R1
050:	ADD	57	0	R0
054:	NEZ	1	303
057:	ADD	0	R1	M222
061:	MUL	M221	1	R3
065:	MUL	M221	1	R2
069:	MUL	1	259	R1
073:	ADD	0	80	R0
077:	NEZ	1	225
080:	MUL	83	1	R2
084:	MUL	1	91	R0
088:	EQZ	0	303
091:	ADD	0	R1	M223
095:	MUL	1	M222	R4
099:	ADD	0	259	R3
103:	ADD	0	225	R2
107:	ADD	225	0	R1
111:	ADD	118	0	R0
115:	EQZ	0	225
118:	ADD	0	M222	R3
122:	ADD	34	0	R2
126:	ADD	133	0	R0
130:	NEZ	1	303
133:	MUL	R1	-1	R1
137:	ADD	M223	R1	R1
141:	MUL	1	148	R0
145:	EQZ	0	259
148:	ADD	R1	0	M223
152:	MUL	1	M221	R4
156:	ADD	0	M222	R3
160:	ADD	12	0	R2
164:	ADD	M132	-2	M224
168:	MUL	M224	2	M224
172:	ADD	M224	3	M224
176:	MUL	M132	-1	M132
180:	ADD	M224	M132	M224
184:	ADD	M224	1	R1
188:	ADD	195	0	R0
192:	NEZ	1	M108
195:	LES	R1	M223	R2
199:	ADD	0	M23	R1
203:	MUL	1	-1	R3
207:	MUL	214	1	R0
21

In [64]:
asm = disassemble(code)

123-element Array{Operation,1}:
 Operation(0, "MVP", ["424"])                
 Operation(2, "INP", ["R1"])                 
 Operation(4, "ADD", ["11", "0", "R0"])      
 Operation(8, "NEZ", ["1", "282"])           
 Operation(11, "MUL", ["1", "18", "R0"])     
 Operation(15, "NEZ", ["1", "259"])          
 Operation(18, "MUL", ["1", "R1", "M221"])   
 Operation(22, "INP", ["R1"])                
 Operation(24, "MUL", ["1", "31", "R0"])     
 Operation(28, "NEZ", ["1", "282"])          
 Operation(31, "MUL", ["38", "1", "R0"])     
 Operation(35, "NEZ", ["1", "259"])          
 Operation(38, "ADD", ["0", "M23", "R2"])    
 ⋮                                           
 Operation(381, "NEZ", ["1", "303"])         
 Operation(384, "EQZ", ["0", "415"])         
 Operation(387, "MUL", ["R-4", "-1", "R-4"]) 
 Operation(391, "ADD", ["R-4", "R-3", "R-4"])
 Operation(395, "MUL", ["R-3", "R-2", "R-2"])
 Operation(399, "MUL", ["R-2", "R-4", "R-4"])
 Operation(403, "MUL", ["R-3", "R-2", "R-3"])
 O